### ISSUE TITLE
Some values in .env cannot be taken

### ISSUE THREAD

**Issue by penguinsam** [sujiba/pihole-unbound-hyperlocal#1]
I found changing some values like WEBTHEME or DNSSEC in .env do not have any effect, I have to manually add config value in the yaml to make it effective.

**Comment by sujiba** [comment]
Hi, 

thanks for the info. 

I've removed the double quotes in the .env (example.env). Now it should work as intended again. 

https://github.com/sujiba/pihole-unbound-hyperlocal/commit/51a062d276ed6dc8acdd288924e404d1833f68ff

**Comment by penguinsam** [comment]
Yes, thanks. I did the same tricks lastly to make it work :)
