### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by mondsen** [sujiba/pihole-unbound-hyperlocal#2]
Hi, thanks for this container and documentation. The questions that I have: what are best practices to keep the containers up-to-date? Are you planning to add watchtower for this or do you have other recommendations?
Additionally: is the root.hints automatically updated?

**Comment by sujiba** [comment]
Hi, 
are you talking about the build process or running the container on a server / host? To automate the build process you could use github actions. To automatically update the container on your server / host you could use watchtower or you could do it manually with 'docker-compose update'.

The root.hints are updated with each docker build when there is a new docker-pihole release, so maybe every one to two months. But they rarely change.

**Comment by mondsen** [comment]
Thanks for the information. That's all I needed. 👍
