### ISSUE TITLE
CACHE_SIZE=0 casues performance impact

### ISSUE THREAD

**Issue by dMopp** [sujiba/pihole-unbound-hyperlocal#9]
Hi,

i see that recommendation again an again but this is technically wrong. Caching should be done in pihole, too, so the already looked up entries are cached as well. (Which end in less CPU usage due to less blacklist lookups)

**Comment by sujiba** [comment]
Hi,

thank you. I've looked into it and will remove the recommendation from the readme.

**Comment by sujiba** [comment]
Also the CUSTOM_CACHE_SIZE in the example.env is set back to the default 10000
